### ISSUE TITLE
Carbonite Nodepack

### ISSUE THREAD

**Issue by TheRealGold** [bark10/barkhouse#16]
Here's a rough thrown together version of the textures.
Hopefully you'll be able to edit em for use with the screwdriver and sounds etc.

https://www.dropbox.com/s/ddkspwwvnwxvxr2/carbonite.rar?dl=0

**Comment by TheRealGold** [comment]
Link to the Github page for the carbonite mod:
https://github.com/TheRealGold/minetest-mod-carbonite

**Comment by bark10** [comment]
Added!
