### ISSUE TITLE
Animated red eye on bone texture

### ISSUE THREAD

**Issue by bark10** [bark10/barkhouse#5]
as suggested by malah:
> Make bones texture bright red and/or add a small red dot near the skull

**Comment by bark10** [comment]
Good  idea. Maybe even an animation? Like a glowing red eye perhaps. @TheRealGold

**Comment by TheRealGold** [comment]
Worked on a few designs and came to this one in the end.
http://imgur.com/a/UQ3tD

**Comment by TheRealGold** [comment]
Edited the file since you guys thought red was intimidating...
Here's an example of how a colour change can make it seem more ethereal.
http://imgur.com/a/2WKQu

**Comment by bark10** [comment]
nice color choice

**Comment by TheRealGold** [comment]
Edited code for new bones texture test:
http://pastebin.com/2y6ZbC6K

**Comment by bark10** [comment]
Can't figure out how to replace the bones. Have created a new node instead, 
**barkhouse:bones**.
